import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Swiper from 'swiper';
// import Swiper styles
import 'swiper/css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yalantics-UI-Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
